
development:
  adapter: postgresql
  database: trellino_development
  host: localhost
  pool: 5
  timeout: 5000
  
  production:
    adapter: postgresql
    database: trellino_production
    pool: 5
    timeout: 5000
  